#!/bin/bash -ex

# Start nginx

HUGO_OUTPUT=${HUGO_DIR}/public

# setup and launch nginx
if pgrep nginx >/dev/null 2>&1; then
    echo "Nginx already running"
else
    NGINXDIR=/usr/share/nginx/html
    rm -rf $NGINXDIR
    mkdir -p ${HUGO_OUTPUT}
    ln -s ${HUGO_OUTPUT} $NGINXDIR
    nginx
fi

