#!/bin/bash -ex

# Start nginx

NANOC_OUTPUT=${NANOC_DIR}/output

# setup and launch nginx
if pgrep nginx >/dev/null 2>&1; then
    echo "Nginx already running"
else
    NGINXDIR=/usr/share/nginx/html
    rm -rf $NGINXDIR
    mkdir -p ${NANOC_OUTPUT}
    ln -s ${NANOC_OUTPUT} $NGINXDIR
    nginx
fi

